### ISSUE TITLE
It is impossible to run `rake db:create` (if the database does not exist)

### ISSUE THREAD

**Issue by fschwahn** [rails/spring#125]
I ran into this issue when I tried to create the database for a project which was already setup to work with spring. My guess is that spring tries to preload the rails app, which fails because the database does not exist, and as a result the rake task fails. There is a simple workaround, namely running `bundle exec rake db:create` to avoid running rake through spring. 

However, it would probably make sense to somehow whitelist this rake task to not run through spring automatically, as it does not need a loaded rails environment anyway.

**Comment by Dorian** [comment]
Seems to happen to a lot of people: http://stackoverflow.com/a/38489616/407213

**Comment by LauraCarvajalSe** [comment]
You should create database again into your project, next, you can review routes.rb and check that all is okay.

**Comment by graciano** [comment]
exact same issue with rails 6.0

**Comment by aoozdemir** [comment]
Yep, somehow problem exists in activerecord 6.0. Did some testing while I was creating a tool to manage migrations outside of rails.

My database connection method is like this;
```ruby
module Connection
  def self.connect!(env)
    # Ref https://github.com/puma/puma#clustered-mode
    ActiveSupport.on_load(:active_record) do
      ::ActiveRecord::Base.connection_pool.disconnect! if ::ActiveRecord::Base.connected?
      ::ActiveRecord::Base.configurations = YAML.load(ERB.new(File.read('config/database.yml')).result) || {}

      config = ::ActiveRecord::Base.configurations[env.to_s]

      ::ActiveRecord::Base.establish_connection(config)
    end
  end
end
```

So, if I use adapter specific methods to create the database using my config file, `rake db:create` works fine. The below code works fine with the connection established using the method above.
```ruby
task :create => :configure_connection do
    database = ActiveRecord::Tasks::PostgreSQLDatabaseTasks.new(@config)
    database.create
    puts "Database created"
end
```

However, I wanted to use `ActiveRecord::Base.connection.create_database` in this task, as I might want to MySQL or whatever. So, if I change the `:create` task to something like this, I get the db doesn't exists error on create.
```ruby
task create: :configure_connection do
  ActiveRecord::Base.connection.create_database(@config['database'])
  puts "Database created"
end
```

The workaround I did is, I excluded the `database` from the initial connection attempt.
```ruby
# ...
::ActiveRecord::Base.establish_connection(config.except('database'))
# ...
```

However, I'm not certain how it'll behave when it comes to migration tasks. I'll update my post here when I tackle that as well.

---

Also, not sure if this issue is directly related to `spring` as it comes from `activerecord`. The error raised from here: https://github.com/rails/rails/blob/3de9669188b543192571932e5cb6f0d5a6ec1043/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L34-L56

**Comment by weefunker** [comment]
This issue completely breaks rails. Why has it been closed without a fix... still?

**Comment by baranyeni** [comment]
I hate when ppl do have the exact same problem with me but the issues are closed! What you guys are doing it been years, retirement with Ruby?

**Comment by andiskiy** [comment]
@baranyeni work solution `createdb {DB_NAME}`. After that everything works

**Comment by AdrienGiboire** [comment]
That's not a solution. `bin/rails db:create` should actually do just that. We are not supposed to have to manually create our db. Otherwise this command is just useless. Plus, it impacts the use of other commands like `db:setup` and such.

I am having this issue currently, and I can't figure out why.
