### ISSUE TITLE
warning: already initialized constant APP_PATH

### ISSUE THREAD

**Issue by janko** [rails/spring#259]
I'm getting a `warning: already initialized constant APP_PATH` error, coming from `bin/rails`. I'm using the latest Spring and Rails 4.

**Comment by chemicalfire** [comment]
Make sure spring is not running. I had to 

    ps aux | grep spring

to find the spring running from a previous instance of the program, then kill the running process. Once I did that the error went away.

**Comment by jkoisch** [comment]
+1 for  @felixbuenemann's proposal ... my error was caused by a gem I am building locally not loading dependencies correctly. I discovered the error by running 

     rake rails:update:bin

which showed the real problem.

**Comment by liwei78** [comment]
update to Rails 4.2.0 with `rake rails:update:bin` solve the error `already initialized constant APP_PATH`

**Comment by prusswan** [comment]
@felixbuenemann is correct. This "error" can be caused by faulty initializers or things that have nothing to with the error description at all.

**Comment by Phaze1D** [comment]
rake rails:update:bin
rake aborted!
LoadError: dlopen(/Users/david/.rvm/gems/ruby-2.2.1/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle, 9): Library not loaded: /usr/local/lib/libmysqlclient.18.dylib
  Referenced from: /Users/david/.rvm/gems/ruby-2.2.1/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle
  Reason: image not found - /Users/david/.rvm/gems/ruby-2.2.1/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle
/Users/david/.rvm/gems/ruby-2.2.1/gems/mysql2-0.3.18/lib/mysql2.rb:31:in `require'
/Users/david/.rvm/gems/ruby-2.2.1/gems/mysql2-0.3.18/lib/mysql2.rb:31:in `<top (required)>'
/Users/david/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
/Users/david/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/david/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
/Users/david/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
/Users/david/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
/Users/david/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
/Users/david/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
/Users/david/Projects/SPS/Devrag/DevragWeb/config/application.rb:7:in `<top (required)>'
/Users/david/Projects/SPS/Devrag/DevragWeb/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace) 


this is caused because i update mysql and i solved it by gem uninstall mysql2 then bundle install

**Comment by felixbuenemann** [comment]
After upgrading to spring 1.4.4 non-spring load errors should no longer be swallowed. Don't forget to run `bin/spring binstub --all` to update your binstubs to the new loader code.

**Comment by ravistm** [comment]
I got it solved this way -> Just uninstall bundler and reinstall, then it will work like a charm
