### ISSUE TITLE
Spring- Doesnt reload database if rolledback and re-migrated

### ISSUE THREAD

**Issue by townie** [rails/spring#288]
I was practicing TDD with rspec/capybara. I wrote my tests for an association (campaign -> user). Ran my migration. realized that I had left off

t.integer user_id, null: false
on my migration so I rolled back and RAKE db:remigrate...

When I ran my spec file, the spring version of my application did not recognize the change had been made on the database.

I had to stop spring and restart it to get it to see the changes.

using `rspec-rails (2.14.2)`

**Comment by edgarjs** [comment]
This seems to be similar to what I'm experiencing, however it seems to be version specific for me.

Our app has been using spring 1.2.0 (rails 4.2.0 but upgraded one version at a time since rails 3 if I remember correctly, we introduced spring in the upgrade to rails 4.0).

Everything runs fine with 1.2.0, but I decided to update to 1.3.3 today and started to experience this mentioned bug, the first time I run the tests it runs ok, then the second time it says I have pending migrations. And then if I just go back to 1.2.0 without even touching the database, it works again.

Not sure where to look for more information. Let me know what commands do I need to run to debug more and I'm happily will do it.

PS: I'm running the tests with `rake test TEST=path/to/test_file.rb`.

Cheers.
