### ISSUE TITLE
deploying a rails app to Heroku

### ISSUE THREAD

**Issue by kalmanh** [rails/spring#450]
Did you guys break this again? :)

https://github.com/rails/spring/issues/192

Deploying apps to Heroku used to work in Rails 4.2.3 until a few days ago when spring 1.4.4 came out.

See the following SO - http://stackoverflow.com/questions/33747990/heroku-doesnt-recognize-spring-gem-even-though-its-listed-in-the-gemfile

I put in a ticket with the Heroku guys and they claim that nothing on their end has changed

**Comment by grosser** [comment]
I think regenerating the binstubs fixes it since we now do 
`raise unless e.message.include?('spring')`

can you reproduce with updated binstubs ?

**Comment by grosser** [comment]
FYI heroku ticket is private and only you can open it ... also not really a heroku issue

**Comment by kalmanh** [comment]
@grosser How do I "regenerate the binstubs"?

Also, you are right that this is not a Heroku issue, but it was affecting Heroku deployment. (This is the 2nd time, the spring gem is affecting me in a weird way https://github.com/spring-guides/gs-spring-boot/issues/17#issuecomment-94003771 :) )

**Comment by grosser** [comment]
`spring binstub --all` ... or `spring binstub` ... basically check that the raise unless include is in the binstubs

**Comment by joallard** [comment]
I had the issue on 1.4.3, but not in 1.6.2 with updated binstubs.

**Comment by halo** [comment]
When I upgraded my spring binstubs (using spring `2.1.1`), I suddenly couldn't deploy to heroku any more because of the same issue:

> Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.

Caused by this underlying exception:

 `/tmp/build_e8e17ca1/vendor/ruby-3.0.1/lib/ruby/3.0.0/rubygems/dependency.rb:311:in 'to_specs': Could not find 'spring' (= 2.1.1) among 265 total gem(s)`

Naturally, spring should **not** be in the production group of the `Gemfile`, so at first I couldn't figure out what the reason was. But then I realized that the upper part of my binstubs was upgraded correctly, but there was one superfluous line still underneath which should not have been there.

This is what was "generated" for `bin/rake`, but that's **wrong**:

```ruby
#!/usr/bin/env ruby
begin
  load File.expand_path('../spring', __FILE__)
rescue LoadError => e
  raise unless e.message.include?('spring')
end
load File.expand_path("spring", __dir__)
require_relative "../config/boot"
require "rake"
Rake.application.run
```

It should have been this, this is correct:

```ruby
#!/usr/bin/env ruby
begin
  load File.expand_path('../spring', __FILE__)
rescue LoadError => e
  raise unless e.message.include?('spring')
end
require_relative "../config/boot"
require "rake"
Rake.application.run
```

So there was a duplicate `load` statement innocently lying around, I think it [came from here](https://github.com/rails/rails/blob/fdce2a22347c96d34245bcbd9d14d6d02366c44f/railties/lib/rails/generators/rails/app/templates/bin/rake.tt#L2). After I removed that superfluous one, everything worked again. The correct loader code [comes from here](https://github.com/rails/spring/blame/577cf01f232bb6dbd0ade7df2df2ac209697e741/lib/spring/client/binstub.rb#L14-L20).

I thought it'd be worth mentioning it because Google led me to this Github issue – which, however, I think can be closed now. Maybe someone else will run into the same thing :)
