### ISSUE TITLE
Pegging CPU core on Apple M1 processor

### ISSUE THREAD

**Issue by henryaj** [rails/spring#636]
Running Ruby 2.7.1 and Spring 2.1.0 (in a Rails 6.0.3.2 app) on an M1 MacBook Air under Rosetta (running the whole shell in x86 mode) I'm seeing spring pegging a whole CPU core (CPU usage of 99%).

Curious to know if others are seeing the same, and what the best way to debug this is!

**Comment by andersoncardoso** [comment]
I'm also seeing this happen on an intel mac on Big Sur. 
I used to work on this same project and same machine and never had this issue. 
After upgrading the OS, whenever I start a process (even an idle `rails console`) the cpu stays at 100% and the fan goes at top speed. 
If I run without spring (`DISABLE_SPRING=1`) then the problem disapears.

**Comment by henryaj** [comment]
Interestingly I'm also seeing this happen with `guard` – maybe something up with the way these two things watch the filesystem for changes?

**Comment by bdibon** [comment]
Same issue, I'm on macOS Big Sur v11.1, using rails v6.1.0. Whenever I run `rails test` a ruby process uses ~100% all my CPU, as you can see on the `ps aux` output below. The process comes back whenever I kill it with the Activity Monitor GUI, the only way to stop it is to exit the terminal session.

```
USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
bdibon            3370 100.0  1.2  4461052 104256   ??  Rs    1:22PM   0:07.83 ruby -I /Users/bdibon/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib -e require 'spring/application/boot'
```

**Comment by andersoncardoso** [comment]
@bdibon have you tried running `spring stop` on the terminal? it might prevent you from having to exit the session.

**Comment by bdibon** [comment]
@andersoncardoso It works ! Nice improvement to my current flow, I guess it opens the door to some `rails t && spring stop` aliasing. Thank you.

**Comment by andersoncardoso** [comment]
Adding some findings here:
This is related to the `spring-watcher-listen` gem (and since this is also happening to `guard`, then the issue must come from `listen`). 
I tried adding several folder patterns to `listener.ignore` in hope that it was because of node_modules or public/packs (from webpack), but nothing worked.
So I found a workaround by using polling mode. For that, you either remove the `spring-watcher-listen` gem or you can add the line below to your `config/spring.rb`:
```
Spring.watch_method = :polling 
```
in my case I added a check for an env var, so my co-workers can still use the evented file watcher while I toggle off.

Notice this will still keep you cpu at around 25 - 30% even without any rails process (server, console, etc) running, just with spring on the background. But it's better than 100% and the cooler fan going crazy.

I hope this helps

**Comment by jeremy** [comment]
Could you please open an issue with the [Listen gem](https://github.com/guard/listen) to troubleshoot? Thank you for reporting!

**Comment by raldred** [comment]
Anyone coming here with this issue, the fix for us was to update the listen gem version in the `Gemfile` to `gem 'listen', '~>3.0', '>= 3.0.5'`

This was fixed in [listen 3.3.0](https://github.com/guard/listen/tree/v3.3.0)

**Comment by perryraskin** [comment]
I'm on an M1 MacBook Pro and recently began using the new Shopify CLI. Ruby is constantly using 100% CPU and causing the fan to turn on (which has never happened before, and I've had this laptop for 6+ months).

Is there something I can do or does Shopify need to push some sort of fix?

**Comment by eatingsnacks** [comment]
@perryraskin Thanks I am seeing this with Shopify CLI as well. I will try your fix. I don't see any mention of it in their issues surprisingly..
